DROP TABLE IF EXISTS user_t;

CREATE TABLE user_t (
    user_id bigint generated by default as identity,
    username varchar(50) not null,
    password varchar(255) not null,
    primary key (user_id)
)
